(eval-when-compile    (require 'color-theme))
(defun color-theme-xy ()
  "Color theme by Xin Yang, created 2011-08-08."
  (interactive)
  (color-theme-install
   '(my-color-theme
     ((background-color . "black")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "green")
      (foreground-color . "white")
      (mouse-color . "#000000"))
     ((ac-fuzzy-cursor-color . "red")
      (buffer-face-mode-face . variable-pitch)
      (compilation-message-face . underline)
      (cscope-use-face . t)
      (curchg-default-cursor-color . "green")
      (curchg-input-method-cursor-color . "Orange")
      (diary-face . diary)
      (gnus-mouse-face . highlight)
      (gnus-summary-selected-face . gnus-summary-selected)
      (hl-line-face . ahei-hl-line-face)
      (ispell-highlight-face . flyspell-incorrect)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (mew-highlight-cursor-line-face . underline)
      (mew-highlight-mouse-line-face . highlight)
      (mew-highlight-url-mouse-face . highlight)
      (mew-use-highlight-x-face . t)
      (org-goto-interface . outline)
      (paren-match-face . paren-face-match)
      (paren-mismatch-face . paren-face-mismatch)
      (paren-no-match-face . paren-face-no-match)
      (term-default-bg-color . "black")
      (term-default-fg-color . "white")
      (view-highlight-face . highlight)
      (vline-face . vline)
      (vline-visual-face . vline-visual)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     ;; (ac-candidate-face ((t (:background "lightgray" :foreground "black"))))
     ;; (ac-completion-face ((t (:background "darkblue" :foreground "white"))))
     ;; (ac-etags-candidate-face ((t (:background "gainsboro" :foreground "deep sky blue"))))
     ;; (ac-etags-selection-face ((t (:background "deep sky blue" :foreground "white"))))
     ;; (ac-gtags-candidate-face ((t (:background "lightgray" :foreground "navy"))))
     ;; (ac-gtags-selection-face ((t (:background "navy" :foreground "white"))))
     ;; (ac-selection-face ((t (:background "blue" :foreground "white"))))
     ;; (ac-verilog-candidate-face ((t (:background "snow3" :foreground "black"))))
     ;; (ac-verilog-selection-face ((t (:background "SlateBlue3" :foreground "black"))))
     ;; (ac-yasnippet-candidate-face ((t (:background "sandybrown" :foreground "black"))))
     ;; (ac-yasnippet-selection-face ((t (:background "coral3" :foreground "white"))))
     ;; (ahei-hl-line-face ((t (:background "#30FF30FF30FF" :inverse-video nil :underline t))))
     ;; (anything-bookmarks-su-face ((t (:foreground "red"))))
     ;; (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     ;; (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     ;; (anything-file-name ((t (:foreground "Blue"))))
     ;; (anything-gentoo-match-face ((t (:foreground "red"))))
     ;; (anything-header ((t (:background "grey20" :foreground "grey90" :box (:line-width -1 :style released-button)))))
     ;; (anything-isearch-match ((t (:background "Yellow"))))
     ;; (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     ;; (anything-visible-mark ((t (:background "green1" :foreground "black"))))
     ;; (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (ascii-ascii-face ((t (:background "SkyBlue4"))))
     (ascii-non-ascii-face ((t (:background "darkolivegreen"))))
     (beautiful-blue-face ((t (:foreground "cornflower blue"))))
     (beautiful-blue-red-face ((t (:background "cornflower blue" :foreground "red"))))
     (bg:erc-color-face0 ((t (:background "White"))))
     (bg:erc-color-face1 ((t (:background "black"))))
     (bg:erc-color-face10 ((t (:background "lightblue1"))))
     (bg:erc-color-face11 ((t (:background "cyan"))))
     (bg:erc-color-face12 ((t (:background "blue"))))
     (bg:erc-color-face13 ((t (:background "deeppink"))))
     (bg:erc-color-face14 ((t (:background "gray50"))))
     (bg:erc-color-face15 ((t (:background "gray90"))))
     (bg:erc-color-face2 ((t (:background "blue4"))))
     (bg:erc-color-face3 ((t (:background "green4"))))
     (bg:erc-color-face4 ((t (:background "red"))))
     (bg:erc-color-face5 ((t (:background "brown"))))
     (bg:erc-color-face6 ((t (:background "purple"))))
     (bg:erc-color-face7 ((t (:background "orange"))))
     (bg:erc-color-face8 ((t (:background "yellow"))))
     (bg:erc-color-face9 ((t (:background "green"))))
     (black-red-face ((t (:background "red" :foreground "black"))))
     (blank-map-face ((t (:bold t :background "Linen" :foreground "Aquamarine3" :weight bold))))
     (blank-space-face ((t (:background "LightYellow" :foreground "Aquamarine3"))))
     (blank-tab-face ((t (:background "Beige" :foreground "Aquamarine3"))))
     (blue-face ((t (:foreground "blue"))))
     (bmkp->-mark ((t (:foreground "Blue"))))
     (bmkp-D-mark ((t (:background "Red" :foreground "Yellow"))))
     (bmkp-a-mark ((t (:background "SkyBlue"))))
     (bmkp-bad-bookmark ((t (:background "Chartreuse1" :foreground "Red"))))
     (bmkp-bookmark-file ((t (:background "Orange" :foreground "DarkGreen"))))
     (bmkp-bookmark-list ((t (:background "DarkRed" :foreground "LightGray"))))
     (bmkp-buffer ((t (:foreground "green"))))
     (bmkp-desktop ((t (:background "DarkBlue" :foreground "PaleGoldenrod"))))
     (bmkp-function ((t (:foreground "DeepPink1"))))
     (bmkp-gnus ((t (:foreground "Magenta"))))
     (bmkp-heading ((t (:foreground "Blue"))))
     (bmkp-info ((t (:foreground "Green"))))
     (bmkp-light-autonamed ((t (:background "#00004AA652F1"))))
     (bmkp-light-fringe-autonamed ((t (:background "#B19E6A64B19E"))))
     (bmkp-light-fringe-non-autonamed ((t (:background "#691DC8A2691D"))))
     (bmkp-light-mark ((t (:background "Plum"))))
     (bmkp-light-non-autonamed ((t (:background "#B19E6A64B19E"))))
     (bmkp-local-directory ((t (:background "DarkBlue" :foreground "HoneyDew2"))))
     (bmkp-local-file-with-region ((t (:foreground "Indianred2"))))
     (bmkp-local-file-without-region ((t (:foreground "Blue"))))
     (bmkp-man ((t (:foreground "Orange4"))))
     (bmkp-non-file ((t (:foreground "gray40"))))
     (bmkp-remote-file ((t (:foreground "pink"))))
     (bmkp-sequence ((t (:foreground "DarkOrange2"))))
     (bmkp-su-or-sudo ((t (:foreground "Red"))))
     (bmkp-t-mark ((t (:foreground "Red"))))
     (bmkp-url ((t (:foreground "yellow"))))
     (bmkp-variable-list ((t (:foreground "Salmon"))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (bookmark-menu-heading ((t (:foreground "green"))))
     (border ((t (:background "black"))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (c-includes-already-face ((t (:foreground "purple"))))
     (c-includes-close-face ((t (:foreground "dark red"))))
     (c-includes-open-face ((t (:foreground "red"))))
     (c-includes-unknown-face ((t (:bold t :foreground "red" :weight bold))))
     (c-nonbreakable-space-face ((t (:background "white" :foreground "red"))))
     (calendar-today ((t (:underline t))))
     (change-log-acknowledgement ((t (:foreground "red"))))
     (change-log-conditionals ((t (:background "black" :foreground "yellow"))))
     (change-log-date ((t (:foreground "magenta"))))
     (change-log-email ((t (:background "black" :foreground "yellow"))))
     (change-log-file ((t (:background "wheat" :foreground "darkorchid2"))))
     (change-log-function ((t (:background "black" :foreground "yellow"))))
     (change-log-list ((t (:background "black" :foreground "cyan"))))
     (change-log-name ((t (:background "darkslateblue" :foreground "chartreuse"))))
     (col-highlight ((t (:background "SlateGray3"))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "cyan1"))))
     (compilation-column-number ((t (:foreground "green"))))
     (compilation-error ((t (:background "red" :foreground "white"))))
     (compilation-info ((t (:foreground "green"))))
     (compilation-line-number ((t (:background "black" :foreground "yellow"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-annotations ((t (:italic t :slant italic))))
     (completions-common-part ((t (nil))))
     (completions-first-difference ((t (nil))))
     (cperl-array-face ((t (:bold t :background "navy" :foreground "yellow" :weight bold))))
     (cperl-hash-face ((t (:italic t :bold t :background "navy" :foreground "Red" :slant italic :weight bold))))
     (cperl-nonoverridable-face ((t (:foreground "orchid1"))))
     (cscope-file-face ((t (:foreground "yellow"))))
     (cscope-function-face ((t (:foreground "cyan"))))
     (cscope-line-face ((t (:foreground "green"))))
     (cscope-line-number-face ((t (:foreground "red"))))
     (cscope-mouse-face ((t (:background "blue" :foreground "white"))))
     (cua-global-mark ((t (:background "yellow1" :foreground "black"))))
     (cua-rectangle ((t (:background "maroon" :foreground "white"))))
     (cua-rectangle-noselect ((t (:background "dimgray" :foreground "white"))))
     (cursor ((t (:background "green"))))
     (custom-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse ((t (:background "grey90" :foreground "black" :box (:line-width 2 :style released-button)))))
     (custom-button-mouse-pressed-unraised ((t (:underline t :background "grey60"))))
     (custom-button-mouse-unraised ((t (:underline t :background "grey60"))))
     (custom-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (custom-button-pressed-unraised ((t (:foreground "violet" :underline t))))
     (custom-button-unraised ((t (:underline t))))
     (custom-changed ((t (:background "blue1" :foreground "white"))))
     (custom-comment ((t (:background "dim gray"))))
     (custom-comment-tag ((t (:foreground "gray80"))))
     (custom-documentation ((t (nil))))
     (custom-face-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-group-tag ((t (:bold t :foreground "light blue" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-group-tag-1 ((t (:bold t :foreground "pink" :weight bold :height 1.2 :family "Sans Serif"))))
     (custom-invalid ((t (:background "red1" :foreground "yellow1"))))
     (custom-link ((t (:foreground "cyan1" :underline t))))
     (custom-modified ((t (:background "blue1" :foreground "white"))))
     (custom-rogue ((t (:background "black" :foreground "pink"))))
     (custom-saved ((t (:underline t))))
     (custom-set ((t (:background "white" :foreground "blue1"))))
     (custom-state ((t (:foreground "lime green"))))
     (custom-themed ((t (:background "blue1" :foreground "white"))))
     (custom-variable-button ((t (:bold t :underline t :weight bold))))
     (custom-variable-tag ((t (:bold t :foreground "light blue" :weight bold))))
     (custom-visibility ((t (:foreground "cyan1" :underline t :height 0.8))))
     (cyan-face ((t (:foreground "cyan"))))
     (darkblue-face ((t (:foreground "blue"))))
     (darkcyan-face ((t (:foreground "cyan"))))
     (darkgreen-face ((t (:foreground "green"))))
     (darkmagenta-face ((t (:foreground "magenta"))))
     (darkred-face ((t (:foreground "red"))))
     (darkyellow-face ((t (:foreground "yellow"))))
     (diary ((t (:bold t :foreground "IndianRed" :weight bold))))
     (diary-anniversary ((t (:foreground "cyan" :background "black"))))
     (diary-button ((t (nil))))
     (diary-time ((t (:foreground "#C892FFFF9957" :background "black"))))
     (diff-added ((t (:foreground "aquamarine"))))
     (diff-changed ((t (:foreground "deep pink"))))
     (diff-context ((t (:foreground "cornflower blue"))))
     (diff-file-header ((t (:foreground "magenta"))))
     (diff-function ((t (:foreground "green"))))
     (diff-header ((t (:foreground "green"))))
     (diff-hunk-header ((t (:foreground "OliveDrab1"))))
     (diff-index ((t (:foreground "cyan"))))
     (diff-indicator-added ((t (:background "white" :foreground "red"))))
     (diff-indicator-changed ((t (:foreground "deep pink"))))
     (diff-indicator-removed ((t (:background "red" :foreground "yellow"))))
     (diff-nonexistent ((t (:foreground "magenta"))))
     (diff-refine-change ((t (:foreground "dark orchid"))))
     (diff-removed ((t (:foreground "red"))))
     (dired-directory ((t (:background "wheat" :foreground "darkorchid2"))))
     (dired-flagged ((t (:background "red" :foreground "white"))))
     (dired-header ((t (:foreground "green"))))
     (dired-ignored ((t (:foreground "grey70"))))
     (dired-lis-mode-line-face ((t (:background "darkmagenta" :foreground "white"))))
     (dired-mark ((t (:background "darkslateblue" :foreground "chartreuse"))))
     (dired-marked ((t (:background "red" :foreground "white"))))
     (dired-perm-write ((t (:foreground "chocolate1"))))
     (dired-symlink ((t (:background "black" :foreground "cyan"))))
     (dired-warning ((t (:background "red" :foreground "white"))))
     (diredp-compressed-file-suffix ((t (:foreground "Yellow"))))
     (diredp-date-time ((t (:foreground "goldenrod1"))))
     (diredp-deletion ((t (:background "Red" :foreground "Yellow"))))
     (diredp-deletion-file-name ((t (:foreground "Red"))))
     (diredp-dir-heading ((t (:background #("bisque4" 0 7 (face (background-color . "#8B8B7D7D6B6B"))) :foreground #("chartreuse1" 0 11 (face (background-color . "#7F7FFFFF0000")))))))
     (diredp-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (diredp-display-msg ((t (:foreground "cornflower blue"))))
     (diredp-exec-priv ((t (:background "LightSteelBlue"))))
     (diredp-executable-tag ((t (:foreground "Red"))))
     (diredp-file-name ((t (:foreground #("lime green" 0 10 (face (background-color . "#3232CDCD3232")))))))
     (diredp-file-suffix ((t (:foreground "DarkMagenta"))))
     (diredp-flag-mark ((t (:background "Blueviolet" :foreground "Yellow"))))
     (diredp-flag-mark-line ((t (:background "Skyblue"))))
     (diredp-ignored-file-name ((t (:foreground "#00006DE06DE0"))))
     (diredp-link-priv ((t (:foreground "DarkOrange"))))
     (diredp-no-priv ((t (:background "LightGray"))))
     (diredp-number ((t (:foreground "#FFFFFFFF7474"))))
     (diredp-other-priv ((t (:background "PaleGoldenrod"))))
     (diredp-rare-priv ((t (:background "SpringGreen" :foreground "Magenta"))))
     (diredp-read-priv ((t (:background "MediumAquamarine"))))
     (diredp-symlink ((t (:foreground "DarkOrange"))))
     (diredp-write-priv ((t (:background "Orchid"))))
     (doremi-last-face ((t (:stipple nil :background "black" :foreground "white" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 90 :width normal :foundry "unknown" :family "DejaVu Sans Mono"))))
     (dropdown-list-face ((t (:stipple nil :background "lightyellow" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "Fixedsys Excelsior 2.00"))))
     (dropdown-list-selection-face ((t (:stipple nil :background "purple" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "unknown" :family "Fixedsys Excelsior 2.00"))))
     (ebrowse-default ((t (nil))))
     (ebrowse-file-name ((t (:italic t :slant italic))))
     (ebrowse-member-attribute ((t (:foreground "red1"))))
     (ebrowse-member-class ((t (:foreground "purple"))))
     (ebrowse-progress ((t (:background "blue1"))))
     (ebrowse-root-class ((t (:bold t :foreground "blue1" :weight bold))))
     (ebrowse-tree-mark ((t (:foreground "red1"))))
     (ecb-default-highlight-face ((t (:background "#729fcf"))))
     (ecb-tag-header-face ((t (:background "#f57900"))))
     (ediff-current-diff-A ((t (:background "DarkSeaGreen3" :foreground "blue violet"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "DodgerBlue1" :foreground "gray11"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "gold1" :foreground "red"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "chocolate2" :foreground "dark slate blue"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (egg-an-tag-mono ((t (:bold t :weight bold :foreground "LightGreen"))))
     (egg-blame ((t (:background "grey15" :foreground "white"))))
     (egg-blame-culprit ((t (:family "Sans Serif" :background "grey15" :foreground "grey60" :height 1.1))))
     (egg-blame-subject ((t (:background "grey15" :family "Sans Serif" :foreground "white" :height 1.1))))
     (egg-branch ((t (:bold t :weight bold :family "Sans Serif" :foreground "Yellow" :height 1.2100000000000002))))
     (egg-branch-mono ((t (:bold t :weight bold :foreground "Yellow"))))
     (egg-diff-add ((t (:foreground "ForestGreen"))))
     (egg-diff-conflict ((t (:foreground "Orange"))))
     (egg-diff-del ((t (:foreground "OrangeRed"))))
     (egg-diff-file-header ((t (:bold t :weight bold :family "Sans Serif" :foreground "LightSlateBlue" :height 1.1))))
     (egg-diff-hunk-header ((t (:background "grey45"))))
     (egg-diff-none ((t (:foreground "grey70"))))
     (egg-electrict-choice ((t (:bold t :family "Sans Serif" :foreground "Cyan" :weight bold))))
     (egg-graph ((t (:foreground "grey30"))))
     (egg-header ((t (:bold t :family "Sans Serif" :weight bold :height 1.1))))
     (egg-help-header-1 ((t (:bold t :foreground "SteelBlue" :family "Sans Serif" :weight bold))))
     (egg-help-header-2 ((t (:family "Sans Serif" :foreground "LightSteelBlue" :height 0.9))))
     (egg-help-key ((t (:bold t :foreground "Yellow" :weight bold :height 0.9))))
     (egg-log-HEAD ((t (:foreground "darkred" :background "lightgreen"))))
     (egg-log-buffer-mark ((t (:bold t :weight bold :foreground "orchid1"))))
     (egg-remote-mono ((t (:bold t :weight bold :foreground "DarkSalmon"))))
     (egg-section-title ((t (:bold t :weight bold :family "Sans Serif" :foreground "PaleGreen" :height 1.2100000000000002))))
     (egg-stash-mono ((t (:bold t :weight bold :foreground "LightGreen"))))
     (egg-tag-mono ((t (:bold t :weight bold :foreground "SkyBlue"))))
     (egg-term ((t (:bold t :weight bold :foreground "Yellow"))))
     (egg-text-1 ((t (:foreground "SteelBlue" :family "Sans Serif"))))
     (egg-text-2 ((t (:foreground "SteelBlue" :family "Sans Serif" :height 1.1))))
     (egg-text-3 ((t (:foreground "SteelBlue" :family "Sans Serif" :height 1.2))))
     (egg-text-4 ((t (:foreground "SteelBlue" :family "Sans Serif" :height 1.4))))
     (egg-text-base ((t (:family "Sans Serif" :foreground "SteelBlue"))))
     (egg-text-help ((t (:foreground "SteelBlue" :family "Sans Serif" :height 0.8))))
     (egg-unmerged-diff-file-header ((t (:bold t :family "Sans Serif" :weight bold :foreground "Orange" :height 1.1))))
     (egg-warning ((t (:bold t :weight bold :foreground "Orange"))))
     (eieio-custom-slot-tag-face ((t (:foreground "light blue"))))
     (eldoc-highlight-function-argument ((t (:foreground "green" :weight normal))))
     (emms-browser-album-face ((t (:foreground "#aaaaff" :height 1.1))))
     (emms-browser-artist-face ((t (:foreground "#aaaaff" :height 1.3))))
     (emms-browser-track-face ((t (:foreground "#aaaaff" :height 1.0))))
     (emms-browser-year/genre-face ((t (:foreground "#aaaaff" :height 1.5))))
     (emms-metaplaylist-mode-current-face ((t (:foreground "red2"))))
     (emms-metaplaylist-mode-face ((t (:foreground "AntiqueWhite3"))))
     (emms-playlist-selected-face ((t (:foreground "SteelBlue3"))))
     (emms-playlist-track-face ((t (:foreground "DarkSeaGreen"))))
     (emms-stream-name-face ((t (:bold t :weight bold))))
     (emms-stream-url-face ((t (:foreground "LightSteelBlue"))))
     (erb-comment-delim-face ((t (:bold t :background "snow3" :foreground "darkgreen" :weight bold))))
     (erb-comment-face ((t (:bold t :background "snow2" :foreground "darkgreen" :weight bold))))
     (erb-delim-face ((t (:background "snow3"))))
     (erb-exec-delim-face ((t (:bold t :background "snow3" :weight bold))))
     (erb-exec-face ((t (:background "snow2"))))
     (erb-face ((t (:background "snow2"))))
     (erb-out-delim-face ((t (:bold t :background "snow3" :foreground "darkred" :weight bold))))
     (erb-out-face ((t (:background "snow2"))))
     (erc-action-face ((t (:bold t :weight bold))))
     (erc-bold-face ((t (:bold t :weight bold))))
     (erc-command-indicator-face ((t (:bold t :weight bold))))
     (erc-default-face ((t (nil))))
     (erc-direct-msg-face ((t (:foreground "IndianRed"))))
     (erc-error-face ((t (:foreground "red"))))
     (erc-header-line ((t (:background "grey90" :foreground "grey20"))))
     (erc-input-face ((t (:foreground "brown"))))
     (erc-inverse-face ((t (:background "Black" :foreground "White"))))
     (erc-my-nick-face ((t (:bold t :foreground "brown" :weight bold))))
     (erc-nick-default-face ((t (:bold t :weight bold))))
     (erc-nick-msg-face ((t (:bold t :foreground "IndianRed" :weight bold))))
     (erc-notice-face ((t (:bold t :foreground "SlateBlue" :weight bold))))
     (erc-prompt-face ((t (:bold t :background "lightBlue2" :foreground "Black" :weight bold))))
     (erc-underline-face ((t (:underline t))))
     (escape-glyph ((t (:foreground "cyan"))))
     (eshell-ls-clutter-face ((t (:bold t :foreground "DimGray" :weight bold))))
     (eshell-ls-executable-face ((t (:bold t :foreground "Coral" :weight bold))))
     (eshell-ls-missing-face ((t (:bold t :foreground "black" :weight bold))))
     (eshell-ls-special-face ((t (:bold t :foreground "Gold" :weight bold))))
     (eshell-ls-symlink-face ((t (:bold t :foreground "White" :weight bold))))
     (ess-jb-comment-face ((t (:italic t :background "#2e3436" :foreground "firebrick" :slant italic))))
     (ess-jb-h1-face ((t (:foreground "dodger blue" :slant normal :height 1.6))))
     (ess-jb-h2-face ((t (:foreground "#6ac214" :slant normal :height 1.4))))
     (ess-jb-h3-face ((t (:foreground "#edd400" :slant normal :height 1.2))))
     (ess-jb-hide-face ((t (:background "#2e3436" :foreground "#243436"))))
     (excerpt ((t (:italic t :slant italic))))
     (ffap ((t (:background "blue" :foreground "red"))))
     (fg:erc-color-face0 ((t (:foreground "White"))))
     (fg:erc-color-face1 ((t (:foreground "black"))))
     (fg:erc-color-face10 ((t (:foreground "lightblue1"))))
     (fg:erc-color-face11 ((t (:foreground "cyan"))))
     (fg:erc-color-face12 ((t (:foreground "blue"))))
     (fg:erc-color-face13 ((t (:foreground "deeppink"))))
     (fg:erc-color-face14 ((t (:foreground "gray50"))))
     (fg:erc-color-face15 ((t (:foreground "gray90"))))
     (fg:erc-color-face2 ((t (:foreground "blue4"))))
     (fg:erc-color-face3 ((t (:foreground "green4"))))
     (fg:erc-color-face4 ((t (:foreground "red"))))
     (fg:erc-color-face5 ((t (:foreground "brown"))))
     (fg:erc-color-face6 ((t (:foreground "purple"))))
     (fg:erc-color-face7 ((t (:foreground "orange"))))
     (fg:erc-color-face8 ((t (:foreground "yellow"))))
     (fg:erc-color-face9 ((t (:foreground "green"))))
     (file-name-shadow ((t (:foreground "grey70"))))
     (fixed ((t (:bold t :weight bold))))
     (fixed-pitch ((t (:family "Monospace"))))
     (flymake-errline ((t (:background "Firebrick4"))))
     (flymake-warnline ((t (:background "DarkBlue"))))
     (flyspell-duplicate ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
     (flyspell-incorrect ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
     (font-lock-builtin-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-comment-delimiter-face ((t (:foreground "chocolate1"))))
     (font-lock-comment-face ((t (:foreground "darkred"))))
     (font-lock-constant-face ((t (:background "darkslateblue" :foreground "chartreuse"))))
     (font-lock-doc-face ((t (:foreground "maroon1"))))
     (font-lock-function-name-face ((t (:background "wheat" :foreground "darkorchid2" :height 1.2))))
     (font-lock-keyword-face ((t (:background "black" :foreground "cyan"))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (:foreground "LightSteelBlue"))))
     (font-lock-regexp-grouping-backslash ((t (:foreground "red"))))
     (font-lock-regexp-grouping-construct ((t (:foreground "yellow"))))
     (font-lock-string-face ((t (:foreground "magenta"))))
     (font-lock-type-face ((t (:foreground "green"))))
     (font-lock-variable-name-face ((t (:background "black" :foreground "#C892FFFF9957"))))
     (font-lock-warning-face ((t (:background "red" :foreground "white"))))
     (fringe ((t (:background "grey10"))))
     (gnus-cite-face-1 ((t (:foreground "#ad7fa8"))))
     (gnus-cite-face-2 ((t (:foreground "sienna4"))))
     (gnus-cite-face-3 ((t (:foreground "khaki4"))))
     (gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
     (gnus-group-mail-1 ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-mail-1-empty ((t (:foreground "light cyan"))))
     (gnus-group-mail-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-mail-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-mail-3 ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-group-mail-3-empty ((t (:foreground "#729fcf"))))
     (gnus-group-mail-low ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-mail-low-empty ((t (:foreground "dodger blue"))))
     (gnus-group-news-1 ((t (:bold t :foreground "light cyan" :weight bold))))
     (gnus-group-news-1-empty ((t (:foreground "light cyan"))))
     (gnus-group-news-2 ((t (:bold t :foreground "turquoise" :weight bold))))
     (gnus-group-news-2-empty ((t (:foreground "turquoise"))))
     (gnus-group-news-3 ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-group-news-3-empty ((t (:foreground "#729fcf"))))
     (gnus-group-news-4 ((t (:bold t :weight bold))))
     (gnus-group-news-4-empty ((t (nil))))
     (gnus-group-news-5 ((t (:bold t :weight bold))))
     (gnus-group-news-5-empty ((t (nil))))
     (gnus-group-news-6 ((t (:bold t :weight bold))))
     (gnus-group-news-6-empty ((t (nil))))
     (gnus-group-news-low ((t (:bold t :foreground "dodger blue" :weight bold))))
     (gnus-group-news-low-empty ((t (:foreground "dodger blue"))))
     (gnus-header-content ((t (:italic t :foreground "#8ae234" :slant italic))))
     (gnus-header-from ((t (:bold t :foreground "#edd400" :weight bold))))
     (gnus-header-name-face ((t (:bold t :foreground "#729fcf" :weight bold))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3" :slant italic :weight bold))))
     (gnus-header-subject ((t (:foreground "#edd400"))))
     (gnus-notify+-modeline-face ((t (:foreground "Gold"))))
     (gnus-signature-face ((t (:italic t :foreground "dark grey" :slant italic))))
     (gnus-splash ((t (:foreground "#cccccc"))))
     (gnus-summary-cancelled ((t (:background "black" :foreground "yellow"))))
     (gnus-summary-high-ancient ((t (:bold t :foreground "rotal blue" :weight bold))))
     (gnus-summary-high-read ((t (:bold t :foreground "lime green" :weight bold))))
     (gnus-summary-high-ticked ((t (:bold t :foreground "tomato" :weight bold))))
     (gnus-summary-high-undownloaded ((t (:bold t :foreground "LightGray" :weight bold))))
     (gnus-summary-high-unread ((t (:bold t :foreground "white" :weight bold))))
     (gnus-summary-low-ancient ((t (:italic t :foreground "lime green" :slant italic))))
     (gnus-summary-low-read ((t (:italic t :foreground "royal blue" :slant italic))))
     (gnus-summary-low-ticked ((t (:italic t :foreground "dark red" :slant italic))))
     (gnus-summary-low-undownloaded ((t (:italic t :foreground "LightGray" :slant italic :weight normal))))
     (gnus-summary-low-unread ((t (:italic t :foreground "white" :slant italic))))
     (gnus-summary-normal-ancient ((t (:foreground "royal blue"))))
     (gnus-summary-normal-read ((t (:foreground "lime green"))))
     (gnus-summary-normal-ticked ((t (:foreground "indian red"))))
     (gnus-summary-normal-undownloaded ((t (:foreground "LightGray" :weight normal))))
     (gnus-summary-normal-unread ((t (:foreground "white"))))
     (gnus-summary-selected ((t (:background "brown4" :foreground "white"))))
     (green-face ((t (:foreground "green"))))
     (green-red-face ((t (:background "red" :foreground "green"))))
     (header-line ((t (:background "grey20" :foreground "grey90" :box nil))))
     (help-argument-name ((t (:italic t :foreground "green" :slant italic))))
     (hide-ifdef-shadow ((t (:foreground "grey70"))))
     (highlight ((t (:background "blue" :foreground "red"))))
     (hl-line ((t (:background "blue" :foreground "red"))))
     (hl-line-face ((t (:background "#30FF30FF30FF" :inverse-video nil :underline t))))
     (hl-paren-face ((t (nil))))
     (hlt-property-highlight ((t (:background "Navy"))))
     (holiday ((t (:background "chocolate4"))))
     (hs-block-flag-face ((t (:background "lightgreen" :foreground "#AF210000AF21" :box (:line-width -1 :style released-button)))))
     (icicle-Completions-instruction-1 ((t (:foreground "#AC4AAC4A0000"))))
     (icicle-Completions-instruction-2 ((t (:foreground "#0000D53CD53C"))))
     (icicle-candidate-part ((t (:background "#451700143197"))))
     (icicle-common-match-highlight-Completions ((t (:foreground "#2017A71F2017"))))
     (icicle-complete-input ((t (:foreground "#B19E6A64B19E"))))
     (icicle-completion ((t (:foreground "#0000D53CD53C"))))
     (icicle-current-candidate-highlight ((t (:background "#69D40A460000"))))
     (icicle-extra-candidate ((t (:background "#4517305D0000"))))
     (icicle-historical-candidate ((t (:foreground "#DBD599DF0000"))))
     (icicle-input-completion-fail ((t (:background "#22225F5F2222"))))
     (icicle-input-completion-fail-lax ((t (:background "#00005E3B5A8D"))))
     (icicle-match-highlight-Completions ((t (:foreground "#1F1FA21CA21C"))))
     (icicle-match-highlight-minibuffer ((t (:underline t))))
     (icicle-mode-line-help ((t (:foreground "#AC4AAC4A0000"))))
     (icicle-multi-command-completion ((t (:background "#8B3500007533" :foreground "#0000D53CD53C"))))
     (icicle-mustmatch-completion ((t (:box (:line-width 2 :color "Blue")))))
     (icicle-proxy-candidate ((t (:background "#316B22970000"))))
     (icicle-saved-candidate ((t (:background "gray20"))))
     (icicle-search-context-level-1 ((t (:background "#FA6CC847FFFF"))))
     (icicle-search-context-level-2 ((t (:background "#C847FFFFE423"))))
     (icicle-search-context-level-3 ((t (:background "#C847D8FEFFFF"))))
     (icicle-search-context-level-4 ((t (:background "#EF46FFFFC847"))))
     (icicle-search-context-level-5 ((t (:background "#FCFCE1E1FFFF"))))
     (icicle-search-context-level-6 ((t (:background "#E1E1FFFFF0F0"))))
     (icicle-search-context-level-7 ((t (:background "#E1E1EAEAFFFF"))))
     (icicle-search-context-level-8 ((t (:background "#F6F5FFFFE1E1"))))
     (icicle-search-current-input ((t (:background "#7F0D00007F0D" :foreground "White"))))
     (icicle-search-main-regexp-current ((t (:background "#00004AA652F1"))))
     (icicle-search-main-regexp-others ((t (:background "#348608690000"))))
     (icicle-special-candidate ((t (:background "#176900004E0A"))))
     (icicle-whitespace-highlight ((t (:background "#000093F402A2"))))
     (icompletep-choices ((t (:foreground "yellow"))))
     (icompletep-determined ((t (:foreground "green"))))
     (icompletep-keys ((t (:foreground "Red"))))
     (icompletep-nb-candidates ((t (:foreground "green"))))
     (ido-first-match ((t (:foreground "yellow" :weight normal))))
     (ido-incomplete-regexp ((t (:background "red" :foreground "white"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "green" :weight normal))))
     (ido-subdir ((t (:foreground "red1"))))
     (ifdef-highlight-face1 ((t (:background "paleturquoise4"))))
     (ifdef-highlight-face2 ((t (:background "paleGreen3"))))
     (ifdef-highlight-face3 ((t (:background "yellow4"))))
     (ifdef-highlight-face4 ((t (:background "pink4"))))
     (info-command-ref-item ((t (:background "LightGray" :foreground "Blue"))))
     (info-file ((t (:background "LightGray" :foreground "Blue"))))
     (info-function-ref-item ((t (:background "LightGray" :foreground "deeppink1"))))
     (info-header-node ((t (:foreground "red"))))
     (info-header-xref ((t (:foreground "cyan1" :underline t))))
     (info-macro-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-menu ((t (:foreground "Blue"))))
     (info-menu-header ((t (:foreground "coral2" :weight normal))))
     (info-menu-star ((t (:background "yellow" :foreground "red"))))
     (info-node ((t (:italic t :bold t :foreground "white" :slant italic :weight bold))))
     (info-quoted-name ((t (:foreground "cornflower blue"))))
     (info-reference-item ((t (:background "white" :foreground "cornflower blue"))))
     (info-single-quote ((t (:background "red" :foreground "white"))))
     (info-special-form-ref-item ((t (:background "LightGray" :foreground "DarkMagenta"))))
     (info-string ((t (:foreground "blue"))))
     (info-syntax-class-item ((t (:background "LightGray" :foreground "DarkGreen"))))
     (info-title-1 ((t (:foreground "yellow"))))
     (info-title-2 ((t (:foreground "lightblue"))))
     (info-title-3 ((t (:foreground "violetred1"))))
     (info-title-4 ((t (:foreground "green"))))
     (info-user-option-ref-item ((t (:background "LightGray" :foreground "Red"))))
     (info-variable-ref-item ((t (:background "LightGray" :foreground "FireBrick"))))
     (info-xref ((t (:foreground "cyan1" :underline t))))
     (info-xref-visited ((t (:foreground "violet" :underline t))))
     (isearch ((t (:background "blue" :foreground "red"))))
     (isearch-fail ((t (:background "red"))))
     (italic ((t (:italic t :slant italic))))
     (js2-error-face ((t (:foreground "red"))))
     (js2-external-variable-face ((t (:foreground "orange"))))
     (js2-function-param-face ((t (:foreground "SeaGreen"))))
     (js2-instance-member-face ((t (:foreground "DarkOrchid"))))
     (js2-jsdoc-html-tag-delimiter-face ((t (:foreground "green"))))
     (js2-jsdoc-html-tag-name-face ((t (:foreground "yellow"))))
     (js2-jsdoc-tag-face ((t (:foreground "SlateGray"))))
     (js2-jsdoc-type-face ((t (:foreground "SteelBlue"))))
     (js2-jsdoc-value-face ((t (:foreground "PeachPuff3"))))
     (js2-magic-paren-face ((t (:underline t))))
     (js2-private-function-call-face ((t (:foreground "goldenrod"))))
     (js2-private-member-face ((t (:foreground "PeachPuff3"))))
     (js2-warning-face ((t (:underline "orange"))))
     (lazy-highlight ((t (:background "white" :foreground "black"))))
     (light-blue-face ((t (:foreground "cornflower blue"))))
     (lightblue-face ((t (:foreground "cornflower blue"))))
     (link ((t (:foreground "cyan1" :underline t))))
     (link-visited ((t (:foreground "violet" :underline t))))
     (linkd-command ((t (:foreground "red" :underline t))))
     (linkd-generic-link ((t (:foreground "yellow"))))
     (linkd-generic-link-name ((t (:foreground "blue"))))
     (linkd-icon ((t (:underline nil))))
     (linkd-star ((t (:foreground "#ffffff"))))
     (linkd-star-name ((t (:background "Pink" :foreground "blue"))))
     (linkd-tag ((t (:foreground "#ffffff"))))
     (linkd-tag-name ((t (:foreground "blue" :underline t))))
     (linkd-wiki ((t (:foreground "FireBrick" :underline t))))
     (linum ((t (:foreground "cyan"))))
     (log-view-file ((t (:bold t :weight bold))))
     (log-view-message ((t (:bold t :weight bold))))
     (magenta-face ((t (:foreground "magenta"))))
     (magit-diff-add ((t (:foreground "#729fcf"))))
     (magit-header ((t (:foreground "#edd400"))))
     (magit-item-highlight ((t (:bold t :weight extra-bold))))
     (makefile-makepp-perl ((t (:background "DarkBlue"))))
     (makefile-shell ((t (nil))))
     (makefile-space ((t (:background "hotpink"))))
     (makefile-targets ((t (:background "wheat" :foreground "darkorchid2"))))
     (match ((t (:background "RoyalBlue3" :foreground "cyan"))))
     (menu ((t (nil))))
     (message-cited-text ((t (:foreground "LightPink1"))))
     (message-header-cc ((t (:bold t :foreground "chartreuse1" :weight bold))))
     (message-header-name ((t (:foreground "green"))))
     (message-header-newsgroups ((t (:italic t :bold t :foreground "yellow" :slant italic :weight bold))))
     (message-header-other ((t (:foreground "VioletRed1"))))
     (message-header-subject ((t (:foreground "OliveDrab1"))))
     (message-header-to ((t (:bold t :foreground "DarkOliveGreen1" :weight bold))))
     (message-header-xheader ((t (:foreground "DeepSkyBlue1"))))
     (message-mml ((t (:foreground "MediumSpringGreen"))))
     (message-separator ((t (:foreground "LightSkyBlue1"))))
     (mew-face-body-cite1 ((t (:foreground "LimeGreen"))))
     (mew-face-body-cite2 ((t (:foreground "SkyBlue"))))
     (mew-face-body-cite3 ((t (:foreground "violet"))))
     (mew-face-body-cite4 ((t (:foreground "Gold"))))
     (mew-face-body-cite5 ((t (:foreground "OrangeRed"))))
     (mew-face-body-comment ((t (:foreground "gray50"))))
     (mew-face-body-url ((t (:foreground "OrangeRed"))))
     (mew-face-eof-message ((t (:bold t :foreground "LimeGreen" :weight bold))))
     (mew-face-eof-part ((t (:bold t :foreground "Gold" :weight bold))))
     (mew-face-header-date ((t (:bold t :foreground "LimeGreen" :weight bold))))
     (mew-face-header-from ((t (:bold t :foreground "Gold" :weight bold))))
     (mew-face-header-important ((t (:bold t :foreground "SkyBlue" :weight bold))))
     (mew-face-header-key ((t (:bold t :foreground "LimeGreen" :weight bold))))
     (mew-face-header-marginal ((t (:bold t :foreground "gray50" :weight bold))))
     (mew-face-header-private ((t (:bold t :weight bold))))
     (mew-face-header-subject ((t (:bold t :foreground "OrangeRed" :weight bold))))
     (mew-face-header-to ((t (:bold t :foreground "violet" :weight bold))))
     (mew-face-header-warning ((t (:bold t :foreground "red" :weight bold))))
     (mew-face-header-xmew ((t (:bold t :foreground "chocolate" :weight bold))))
     (mew-face-header-xmew-bad ((t (:bold t :foreground "red" :weight bold))))
     (mew-face-mark-delete ((t (:foreground "OrangeRed"))))
     (mew-face-mark-escape ((t (:foreground "violet"))))
     (mew-face-mark-refile ((t (:foreground "LimeGreen"))))
     (mew-face-mark-review ((t (:foreground "SkyBlue"))))
     (mew-face-mark-unlink ((t (:foreground "Gold"))))
     (mew-face-mark-unread ((t (nil))))
     (minibuffer-prompt ((t (:foreground "cyan"))))
     (moccur-current-line-face ((t (:background "blue" :foreground "red" :underline t))))
     (moccur-face ((t (:background "white" :foreground "red" :weight normal))))
     (mode-line ((t (:background "lightgreen" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:background "HotPink3" :foreground "yellow"))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "white" :foreground "black" :box (:line-width -1 :color "grey40" :style nil) :weight light))))
     (mode-line-lines-face ((t (:background "dark slate blue" :foreground "yellow"))))
     (modelinepos-column-warning ((t (:foreground "Red"))))
     (mouse ((t (:background "#000000"))))
     (next-error ((t (:background "#4CAA4CAA4CAA"))))
     (nobreak-space ((t (:foreground "cyan" :underline t))))
     (notify-user-of-mode ((t (:foreground "cyan"))))
     (org-agenda-clocking ((t (:background "SkyBlue4"))))
     (org-agenda-column-dateline ((t (:family "DejaVu Sans Mono" :weight normal :slant normal :underline nil :strike-through nil :background "grey30" :height 90))))
     (org-agenda-current-time ((t (:foreground "LightGoldenrod"))))
     (org-agenda-date ((t (:bold t :weight bold :foreground "#6ac214"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "#edd400" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "dodger blue" :weight bold))))
     (org-agenda-diary ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 90))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "PaleGreen"))))
     (org-agenda-restriction-lock ((t (:background "skyblue4"))))
     (org-agenda-structure ((t (:bold t :foreground "tomato" :weight bold))))
     (org-archived ((t (:foreground "grey70"))))
     (org-block ((t (:foreground "#bbbbbc"))))
     (org-block-background ((t (nil))))
     (org-block-begin-line ((t (:foreground "darkred"))))
     (org-block-end-line ((t (:foreground "darkred"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-checkbox-statistics-done ((t (:bold t :weight bold :foreground "ForestGreen"))))
     (org-checkbox-statistics-todo ((t (:bold t :weight bold :foreground "Red"))))
     (org-clock-overlay ((t (:background "SkyBlue4"))))
     (org-code ((t (:foreground "grey70"))))
     (org-column ((t (:background "grey30" :strike-through nil :underline nil :slant normal :weight normal :height 90 :family "DejaVu Sans Mono"))))
     (org-column-title ((t (:bold t :background "grey30" :underline t :weight bold))))
     (org-date ((t (:foreground "magenta3" :underline t))))
     (org-default ((t (:family "DejaVu Sans Mono" :foundry "unknown" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "white" :background "black" :stipple nil :height 90))))
     (org-document-info ((t (:foreground "pale turquoise"))))
     (org-document-info-keyword ((t (:foreground "grey70"))))
     (org-document-title ((t (:bold t :foreground "pale turquoise" :weight bold :height 1.44))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "LightSkyBlue"))))
     (org-ellipsis ((t (:foreground "LightGoldenrod" :underline t))))
     (org-eval ((t (:foreground "grey60"))))
     (org-footnote ((t (:foreground "magenta3" :underline t))))
     (org-formula ((t (:foreground "chocolate1"))))
     (org-habit-alert-face ((t (:background "gold"))))
     (org-habit-alert-future-face ((t (:background "darkgoldenrod"))))
     (org-habit-clear-face ((t (:background "blue"))))
     (org-habit-clear-future-face ((t (:background "midnightblue"))))
     (org-habit-overdue-face ((t (:background "firebrick"))))
     (org-habit-overdue-future-face ((t (:background "darkred"))))
     (org-habit-ready-face ((t (:background "forestgreen"))))
     (org-habit-ready-future-face ((t (:background "darkgreen"))))
     (org-headline-done ((t (:foreground "LightSalmon"))))
     (org-hide ((t (:foreground "#2e3436"))))
     (org-latex-and-export-specials ((t (:foreground "burlywood"))))
     (org-level-1 ((t (:bold t :foreground #("chartreuse" 0 10 (face (background-color . "#7F7FFFFF0000"))) :weight bold :height 1.5))))
     (org-level-2 ((t (:bold t :foreground "#edd400" :weight bold :height 1.2))))
     (org-level-3 ((t (:bold t :foreground "#6ac214" :weight bold :height 1.0))))
     (org-level-4 ((t (:bold t :foreground "tomato" :weight bold :height 1.0))))
     (org-level-5 ((t (:foreground "green"))))
     (org-level-6 ((t (:background "darkslateblue" :foreground "chartreuse"))))
     (org-level-7 ((t (:foreground "LightSteelBlue"))))
     (org-level-8 ((t (:foreground "magenta"))))
     (org-link ((t (:background "#2e3436" :foreground "skyblue2"))))
     (org-meta-line ((t (:foreground "darkred"))))
     (org-mode-line-clock ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "lightgreen"))))
     (org-mode-line-clock-overrun ((t (:box (:line-width -1 :style released-button) :foreground "black" :background "red"))))
     (org-mtags ((t (:foreground "grey70"))))
     (org-property-value ((t (nil))))
     (org-quote ((t (:italic t :foreground "#bbbbbc" :slant italic))))
     (org-scheduled ((t (:foreground "PaleGreen"))))
     (org-scheduled-previously ((t (:foreground "chocolate1"))))
     (org-scheduled-today ((t (:foreground "PaleGreen"))))
     (org-sexp-date ((t (:foreground "Cyan"))))
     (org-special-keyword ((t (:foreground "brown"))))
     (org-table ((t (:foreground "LightSkyBlue"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "LightGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "chocolate1"))))
     (org-verbatim ((t (:italic t :foreground "#eeeeec" :underline t :slant italic))))
     (org-verse ((t (:italic t :foreground "#bbbbbc" :slant italic))))
     (org-warning ((t (:foreground "white" :background "red"))))
     (orgpan-active-field ((t (:foreground "red" :background "blue"))))
     (orgpan-field ((t (:background "dim gray"))))
     (orgpan-spaceline ((t (:height 0.2))))
     (outline-1 ((t (:foreground "darkorchid2" :background "wheat" :height 1.2))))
     (outline-2 ((t (:foreground "#C892FFFF9957" :background "black"))))
     (outline-3 ((t (:foreground "cyan" :background "black"))))
     (outline-4 ((t (:foreground "darkred"))))
     (outline-5 ((t (:foreground "green"))))
     (outline-6 ((t (:foreground "chartreuse" :background "darkslateblue"))))
     (outline-7 ((t (:foreground "LightSteelBlue"))))
     (outline-8 ((t (:foreground "magenta"))))
     (paren-face-match ((t (:background "magenta" :foreground "yellow"))))
     (paren-face-mismatch ((t (:background "red" :foreground "white"))))
     (paren-face-no-match ((t (:background "yellow" :foreground "black"))))
     (popup-face ((t (:background "lightgray" :foreground "black"))))
     (popup-isearch-match ((t (:background "sky blue"))))
     (popup-menu-face ((t (:background "lightgray" :foreground "black"))))
     (popup-menu-selection-face ((t (:background "steelblue" :foreground "white"))))
     (popup-scroll-bar-background-face ((t (:background "gray"))))
     (popup-scroll-bar-foreground-face ((t (:background "black"))))
     (popup-tip-face ((t (:background "khaki1" :foreground "black"))))
     (pulse-highlight-face ((t (:background "#AAAA33"))))
     (pulse-highlight-start-face ((t (:background "#AAAA33"))))
     (query-replace ((t (:background "blue" :foreground "red"))))
     (red-blue-face ((t (:background "blue" :foreground "red"))))
     (red-face ((t (:foreground "red"))))
     (red-yellow-face ((t (:background "yellow" :foreground "red"))))
     (region ((t (:background "lightgreen" :foreground "darkred"))))
     (scroll-bar ((t (:background "#efebe7" :foreground "#101010"))))
     (search-buffers-face ((t (:bold t :background "SkyBlue" :foreground "Black" :weight bold))))
     (search-buffers-header-face ((t (:bold t :background "gray20" :foreground "azure3" :weight bold))))
     (secondary-selection ((t (:background "SkyBlue4"))))
     (semantic-decoration-on-includes ((t (nil))))
     (semantic-decoration-on-private-members-face ((t (:background "#200000"))))
     (semantic-decoration-on-protected-members-face ((t (:background "#000020"))))
     (semantic-decoration-on-unknown-includes ((t (:background "#900000"))))
     (semantic-decoration-on-unparsed-includes ((t (:background "#555500"))))
     (semantic-highlight-edits-face ((t (:background "gray20"))))
     (semantic-highlight-func-current-tag-face ((t (:background "gray20"))))
     (semantic-tag-boundary-face ((t (:overline "cyan"))))
     (semantic-unmatched-syntax-face ((t (:underline "red"))))
     (senator-intangible-face ((t (:foreground "gray75"))))
     (senator-momentary-highlight-face ((t (:background "gray30"))))
     (senator-read-only-face ((t (:background "#664444"))))
     (sgml-namespace ((t (:foreground "LightSteelBlue"))))
     (sh-escaped-newline ((t (:foreground "magenta"))))
     (sh-heredoc ((t (:foreground "deeppink"))))
     (sh-quoted-exec ((t (:foreground "salmon"))))
     (shadow ((t (:foreground "grey70"))))
     (show-paren-match ((t (:background "magenta" :foreground "yellow"))))
     (show-paren-mismatch ((t (:background "red" :foreground "white"))))
     (show-tabs-space ((t (:background "yellow1"))))
     (show-tabs-tab ((t (:background "red1"))))
     (speedbar-button-face ((t (:foreground "green3"))))
     (speedbar-directory-face ((t (:foreground "light blue"))))
     (speedbar-file-face ((t (:foreground "cyan"))))
     (speedbar-highlight-face ((t (:background "sea green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "yellow"))))
     (sr-active-path-face ((t (:bold t :background "#ace6ac" :foreground "yellow" :weight bold :height 120))))
     (sr-alt-marked-dir-face ((t (:bold t :foreground "DeepPink" :weight bold))))
     (sr-alt-marked-file-face ((t (:foreground "DeepPink"))))
     (sr-broken-link-face ((t (:italic t :foreground "red" :slant italic))))
     (sr-clex-hotchar-face ((t (:bold t :foreground "red" :weight bold))))
     (sr-compressed-face ((t (:foreground "magenta"))))
     (sr-directory-face ((t (:bold t :foreground "blue1" :weight bold))))
     (sr-editing-path-face ((t (:bold t :background "red" :foreground "yellow" :weight bold :height 120))))
     (sr-encrypted-face ((t (:foreground "DarkOrange1"))))
     (sr-highlight-path-face ((t (:bold t :background "yellow" :foreground "#ace6ac" :weight bold :height 120))))
     (sr-html-face ((t (:foreground "DarkOliveGreen"))))
     (sr-log-face ((t (:foreground "brown"))))
     (sr-marked-dir-face ((t (:bold t :foreground "red" :weight bold))))
     (sr-marked-file-face ((t (:foreground "red"))))
     (sr-mirror-path-face ((t (:bold t :background "blue" :foreground "yellow" :weight bold :height 120))))
     (sr-modeline-separator-face ((t (:height 0.3))))
     (sr-packaged-face ((t (:foreground "DarkMagenta"))))
     (sr-passive-path-face ((t (:bold t :background "white" :foreground "lightgray" :weight bold :height 120))))
     (sr-symlink-directory-face ((t (:italic t :foreground "blue1" :slant italic))))
     (sr-symlink-face ((t (:italic t :foreground "DeepSkyBlue" :slant italic))))
     (sr-tabs-active-face ((t (:bold t :family "Sans Serif" :background "white" :weight bold :height 0.9))))
     (sr-tabs-inactive-face ((t (:family "Sans Serif" :background "gray95" :height 0.9))))
     (sr-tabs-separator-face ((t (:height 0.3))))
     (sr-xml-face ((t (:foreground "DarkGreen"))))
     (svn-status-directory-face ((t (:foreground "lightskyblue1"))))
     (svn-status-filename-face ((t (:foreground "yellow"))))
     (svn-status-locked-face ((t (:bold t :foreground "Red" :weight bold))))
     (svn-status-marked-face ((t (:foreground "palegreen2"))))
     (svn-status-marked-popup-face ((t (:foreground "palegreen2"))))
     (svn-status-switched-face ((t (:foreground "Aquamarine"))))
     (svn-status-update-available-face ((t (:foreground "yellow"))))
     (synonyms-heading ((t (:foreground "Yellow"))))
     (synonyms-link ((t (:foreground "Yellow" :underline t))))
     (synonyms-mouse-face ((t (:background "DarkCyan"))))
     (synonyms-search-text ((t (:foreground "Red"))))
     (template-message-face ((t (:bold t :weight bold))))
     (tool-bar ((t (:background "#efebe7" :foreground "#101010" :box (:line-width 1 :style released-button)))))
     (tool-tips ((t (:family "Sans Serif" :background "lightyellow" :foreground "black"))))
     (tooltip ((t (:background "lightyellow" :foreground "black" :family "Sans Serif"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (underline-face ((t (:underline t))))
     (underline-green-face ((t (:foreground "green" :underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (view-mode-mode-line-face ((t (:background "red" :foreground "white"))))
     (vline ((t (:background "light steel blue"))))
     (vline-visual ((t (:background "gray90"))))
     (w3m-anchor ((t (:foreground "cyan"))))
     (w3m-arrived-anchor ((t (:foreground "magenta"))))
     (w3m-bold ((t (:bold t :weight bold))))
     (w3m-current-anchor ((t (:bold t :underline t :weight bold))))
     (w3m-form-button ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-mouse ((t (:background "DarkSeaGreen1" :foreground "black" :box (:line-width 2 :style released-button)))))
     (w3m-form-button-pressed ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
     (w3m-header-line-location-content ((t (:background "Gray20" :foreground "LightGoldenrod"))))
     (w3m-header-line-location-title ((t (:background "Gray20" :foreground "Cyan"))))
     (w3m-history-current-url ((t (:background "SkyBlue4" :foreground "LightSkyBlue"))))
     (w3m-image ((t (:foreground "PaleGreen"))))
     (w3m-image-anchor ((t (:background "dark green"))))
     (w3m-insert ((t (:foreground "orchid"))))
     (w3m-italic ((t (:italic t :slant italic))))
     (w3m-strike-through ((t (:strike-through t))))
     (w3m-tab-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-mouse ((t (:background "Gray75" :foreground "white" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected ((t (:background "Gray90" :foreground "black" :box (:line-width -1 :style released-button)))))
     (w3m-tab-selected-background ((t (:background "LightSteelBlue" :foreground "black"))))
     (w3m-tab-selected-retrieving ((t (:background "Gray90" :foreground "red" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-retrieving ((t (:background "Gray70" :foreground "OrangeRed" :box (:line-width -1 :style released-button)))))
     (w3m-tab-unselected-unseen ((t (:background "Gray70" :foreground "Gray20" :box (:line-width -1 :style released-button)))))
     (w3m-underline ((t (:underline t))))
     (which-func ((t (:background "dark magenta" :foreground "yellow2"))))
     (white-face ((t (:foreground "white"))))
     (white-red-face ((t (:background "red" :foreground "white"))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "lime green"))))
     (widget-field ((t (:background "dim gray"))))
     (widget-inactive ((t (:foreground "grey70"))))
     (widget-mouse-face ((t (:bold t :background "brown4" :foreground "white" :weight bold))))
     (widget-single-line-field ((t (:background "dim gray"))))
     (woman-addition ((t (:foreground "yellow"))))
     (woman-bold ((t (:bold t :foreground "red" :weight bold))))
     (woman-italic ((t (:italic t :foreground "green" :underline t :slant italic))))
     (woman-unknown ((t (:foreground "blue"))))
     (wuxch-dired-avi-face ((t (:background "black" :foreground "yellow"))))
     (wuxch-dired-doc-face ((t (:background "red" :foreground "white"))))
     (wuxch-dired-elisp-face ((t (:background "black" :foreground "cyan"))))
     (wuxch-dired-exe-face ((t (:background "wheat" :foreground "darkorchid2"))))
     (xref-error-face ((t (:foreground "red"))))
     (xref-keyword-face ((t (:foreground "blue"))))
     (xref-list-default-face ((t (nil))))
     (xref-list-pilot-face ((t (:foreground "navy"))))
     (xref-list-symbol-face ((t (:foreground "Sienna"))))
     (yas/field-debug-face ((t (nil))))
     (yas/field-highlight-face ((t (:background "DimGrey"))))
     (yellow-blue-face ((t (:background "blue" :foreground "yellow"))))
     (yellow-face ((t (:foreground "yellow"))))
     (yellow-forestgreen-face ((t (:background "forest green" :foreground "yellow"))))
     (yellow-red-face ((t (:background "red" :foreground "yellow"))))
     (zjl-hl-elisp-function-call-face ((t (:foreground "cornflower blue" :height 1.15))))
     (zjl-hl-elisp-number-face ((t (:foreground "red"))))
     (zjl-hl-elisp-setq-face ((t (:foreground "cyan"))))
     (zjl-hl-font-lock-bracket-face ((t (:bold t :foreground "firebrick3" :weight bold :height 1.2))))
     (zjl-hl-function-call-face ((t (:foreground "cornflower blue" :height 1.15))))
     (zjl-hl-local-variable-reference-face ((t (nil))))
     (zjl-hl-member-point-face ((t (:foreground "PaleGreen"))))
     (zjl-hl-member-reference-face ((t (:foreground "#f4a957"))))
     (zjl-hl-number-face ((t (:foreground "red"))))
     (zjl-hl-operators-face ((t (:bold t :foreground "Green" :weight bold))))
     (zjl-hl-parameters-reference-face ((t (:bold t :foreground "Yellow" :weight bold)))))))
(add-to-list 'color-themes '(my-color-theme  "THEME NAME" "YOUR NAME"))
